### ISSUE TITLE
Исключить из синхронизации папку obj

### ISSUE THREAD

**Issue by Andrewma05** [Andrewma05/iCRM#3]
Исключить из синхронизации папку obj для проекта (библиотека классов) Connectors. Если ее оставить не компилируется решение локально :(
Там есть в программке когда включаешь исключения она автоматом генерит прекрасный файл, и прописывает исключения этих файлов

**Comment by akmetjuk** [comment]
Это "твой" проект, поэтому исключения можешь сделать только ты!

**Comment by Andrewma05** [comment]
ну я включил их значит должно работать
